-- Tworzenie tabeli audytowej dla tabeli BOOKS
CREATE TABLE BOOKS_AUD (
                           EVENT_ID INT(11) NOT NULL AUTO_INCREMENT,
                           EVENT_DATE DATETIME NOT NULL,
                           EVENT_TYPE VARCHAR(10) DEFAULT NULL,
                           BOOK_ID INT(11) NOT NULL,
                           OLD_TITLE VARCHAR(255),
                           NEW_TITLE VARCHAR(255),
                           OLD_PUBYEAR INT,
                           NEW_PUBYEAR INT,
                           OLD_BESTSELLER BOOLEAN,
                           NEW_BESTSELLER BOOLEAN,
                           PRIMARY KEY (EVENT_ID)
);

-- Tworzenie tabeli audytowej dla tabeli READERS
CREATE TABLE READERS_AUD (
                             EVENT_ID INT(11) NOT NULL AUTO_INCREMENT,
                             EVENT_DATE DATETIME NOT NULL,
                             EVENT_TYPE VARCHAR(10) DEFAULT NULL,
                             READER_ID INT(11) NOT NULL,
                             OLD_FIRSTNAME VARCHAR(255),
                             NEW_FIRSTNAME VARCHAR(255),
                             OLD_LASTNAME VARCHAR(255),
                             NEW_LASTNAME VARCHAR(255),
                             OLD_PESELID INT(11) NOT NULL,
                             NEW_PESELID INT(11) NOT NULL,
                             OLD_VIP_LEVEL VARCHAR(50),
                             NEW_VIP_LEVEL VARCHAR(50),
                             PRIMARY KEY (EVENT_ID)
);

-- Wyzwalacze dla tabeli BOOKS

-- Wyzwalacz po operacji INSERT
DELIMITER $$

CREATE TRIGGER books_after_insert AFTER INSERT ON BOOKS
    FOR EACH ROW
    INSERT INTO BOOKS_AUD (EVENT_DATE, EVENT_TYPE, BOOK_ID, NEW_TITLE, NEW_PUBYEAR, NEW_BESTSELLER)
    VALUES (NOW(), 'INSERT', NEW.BOOK_ID, NEW.TITLE, NEW.PUBYEAR, NEW.BESTSELLER);

END $$

DELIMITER ;

-- Wyzwalacz po operacji DELETE
DELIMITER $$

CREATE TRIGGER books_after_delete AFTER DELETE ON BOOKS
    FOR EACH ROW
    INSERT INTO BOOKS_AUD (EVENT_DATE, EVENT_TYPE, BOOK_ID, OLD_TITLE, OLD_PUBYEAR, OLD_BESTSELLER)
    VALUES (NOW(), 'DELETE', OLD.BOOK_ID, OLD.TITLE, OLD.PUBYEAR, OLD.BESTSELLER);

END $$

DELIMITER ;

-- Wyzwalacz po operacji UPDATE
DELIMITER $$

CREATE TRIGGER books_after_update AFTER UPDATE ON BOOKS
    FOR EACH ROW
    INSERT INTO BOOKS_AUD (EVENT_DATE, EVENT_TYPE, BOOK_ID, OLD_TITLE, NEW_TITLE, OLD_PUBYEAR, NEW_PUBYEAR, OLD_BESTSELLER, NEW_BESTSELLER)
    VALUES (NOW(), 'UPDATE', NEW.BOOK_ID, OLD.TITLE, NEW.TITLE, OLD.PUBYEAR, NEW.PUBYEAR, OLD.BESTSELLER, NEW.BESTSELLER);

END $$

DELIMITER ;

-- Wyzwalacze dla tabeli READERS

-- Wyzwalacz po operacji INSERT
DELIMITER $$

CREATE TRIGGER readers_after_insert AFTER INSERT ON READERS
    FOR EACH ROW
    INSERT INTO READERS_AUD (EVENT_DATE, EVENT_TYPE, READER_ID, NEW_FIRSTNAME, NEW_LASTNAME, NEW_PESELID, NEW_VIP_LEVEL)
    VALUES (NOW(), 'INSERT', NEW.READER_ID, NEW.FIRSTNAME, NEW.LASTNAME, NEW.PESELID, NEW.VIP_LEVEL);

END $$

DELIMITER ;

-- Wyzwalacz po operacji DELETE
DELIMITER $$

CREATE TRIGGER readers_after_delete AFTER DELETE ON READERS
    FOR EACH ROW
    INSERT INTO READERS_AUD (EVENT_DATE, EVENT_TYPE, READER_ID, OLD_FIRSTNAME, OLD_LASTNAME, OLD_PESELID, OLD_VIP_LEVEL)
    VALUES (NOW(), 'DELETE', OLD.READER_ID, OLD.FIRSTNAME, OLD.LASTNAME, OLD.PESELID, OLD.VIP_LEVEL);

END $$

DELIMITER ;

-- Wyzwalacz po operacji UPDATE
DELIMITER $$

CREATE TRIGGER readers_after_update AFTER UPDATE ON READERS
    FOR EACH ROW
    INSERT INTO READERS_AUD (EVENT_DATE, EVENT_TYPE, READER_ID, OLD_FIRSTNAME, NEW_FIRSTNAME, OLD_LASTNAME, NEW_LASTNAME, OLD_PESELID, NEW_PESELID, OLD_VIP_LEVEL, NEW_VIP_LEVEL)
    VALUES (NOW(), 'UPDATE', NEW.READER_ID, OLD.FIRSTNAME, NEW.FIRSTNAME, OLD.LASTNAME, NEW.LASTNAME, OLD.PESELID, NEW.PESELID, OLD.VIP_LEVEL, NEW.VIP_LEVEL);

END $$

DELIMITER ;